#69 api tutoriais
fga-eps-mds/2023-1-schedula-front pull request #10
Opened 2023-05-15 23:38 UTC by italovinicius18

# ✨ New Feature

## 📖 Description

Adicionando conexão ao microserviço de gerenciador de tutoriais. Já foi validado na develop

### 🎫 Issues

[Issue #69](https://github.com/fga-eps-mds/2023-1-schedula-doc/issues/69)

## 👩‍💻 Reviewer Notes

## 📑 Test Plan

Poderia testar com um endpoint incorreto, verificar se aparece o erro:

![image](https://github.com/fga-eps-mds/2023-1-schedula-front/assets/39673124/35411b7d-998f-4809-98de-c4707d606bf6)

E depois testar com o endpoint correto.

## ⏭ Next Steps

2023-05-16 00:36 UTC, AlvaroLeles commented
Esse PR é pra Main mesmo?

2023-05-16 00:56 UTC, AlvaroLeles requested changes

2023-05-16 00:56 UTC, AlvaroLeles commented on src/pages/usuarios/index.tsx
![image](https://github.com/fga-eps-mds/2023-1-schedula-front/assets/54085562/b55763ae-d73c-4e0b-85a8-dc21b419e94a)
Ainda não é possível editar o usuário

2023-05-16 12:26 UTC, italovinicius18 commented on src/pages/usuarios/index.tsx
@AlvaroLeles a correção do bug foi adicionada, mas o erro não é do front é um erro do back-end, acredito que seja por que a chave é única do email e quando ele edita já existe esse email na tabela

2023-05-18 03:08 UTC, AlvaroLeles commented on src/pages/usuarios/index.tsx
Testei novamente nas condições adequadas e funcionou corretamente. Acredito que podemos mandar sim para a main

2023-05-18 03:08 UTC, AlvaroLeles approved these changes

2023-05-18 03:09 UTC, merged